version: "3.8"
services:
  vault-server:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/vault/file:rw
      - ./config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/vault.json
    networks:
      vault-network:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server
networks:
  vault-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24